apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-todo-app
  template:
    metadata:
      labels:
        app: simple-todo-app
    spec:
      containers:
      - name: simple-todo-app
        image: ashhar001/simple-todo-app:latest
        ports:
        - containerPort: 8080
